My first draft of potential bot finder
serlo/serlo-bot pull request #1
Opened 2022-03-04 11:26 UTC by kellyshor

2022-03-07 13:36 UTC, hugotiburtino requested changes
Mainly I suggested refactoring changes. You may accept or not, it is your call. 
The only things that really have to be changed are the typos in the unhelpful words.

2022-03-07 13:36 UTC, hugotiburtino commented on notebooks/2022-04-03potential_bot.ipynb
> +    "    joinedString = \"\".join(user[1])\n",
Why it isn't `joinedString = user[1]` (or maybe `description = user[1]` enough here?

2022-03-07 13:36 UTC, hugotiburtino commented on notebooks/2022-04-03potential_bot.ipynb
> +    "potentialBots = np.empty((0,2))\n",
Same suggestion about this and other vars: instead of using camel case it is more common to use snake case in Python.

2022-03-07 13:36 UTC, hugotiburtino commented on notebooks/2022-04-03potential_bot.ipynb
> +    "                      'type','level','children','p','h','ttachment','ile','layout',\n",
typo here: `attachment`

And `ile` isn't maybe `file`?

2022-03-07 13:36 UTC, hugotiburtino commented on notebooks/2022-04-03potential_bot.ipynb
> +    "    elif descLen > 1500:\n",
could we find a descriptive name to this [magical number](https://stackoverflow.com/questions/47882/what-is-a-magic-number-and-why-is-it-bad)? Something like MAX_DESCRIPTION_SIZE or something better ?

2022-03-07 13:36 UTC, hugotiburtino commented on notebooks/2022-04-03potential_bot.ipynb
> +    "        potentialBots = np.vstack([potentialBots, user])\n",
We could refactor these lines that way:
```
    MAX_DESCRIPTION_SIZE = 1500
    
    if len(splitString) > MAX_DESCRIPTION_SIZE:
        potentialBots = np.vstack([potentialBots, user])
        continue
    
    for word in splitString:
        if(flagged_word(word)):
            potentialBots = np.vstack([potentialBots, [user[0], readable(splitString)]])
            break
```

2022-03-10 13:29 UTC, kulla approved these changes

2022-03-10 13:29 UTC, merged